[package]
name = "tantivy"
version = "0.5.1"
authors = ["Paul Masurel <paul.masurel@gmail.com>"]
license = "MIT"
categories = ["database-implementations", "data-structures"]
description = """Tantivy is a search engine library."""
documentation = "https://tantivy-search.github.io/tantivy/tantivy/index.html"
homepage = "https://github.com/tantivy-search/tantivy"
repository = "https://github.com/tantivy-search/tantivy"
readme = "README.md"
keywords = ["search", "information", "retrieval"]

[dependencies]
byteorder = "1.0"
lazy_static = "0.2.1"
tinysegmenter = "0.1.0"
regex = "0.2"
fst = {version="0.2", default-features=false}
atomicwrites = {version="0.1", optional=true}
log = "0.3.6"
combine = "2.2"
tempdir = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
num_cpus = "1.2"
itertools = "0.5.9"
bit-set = "0.4.0"
uuid = { version = "0.6", features = ["v4", "serde"] }
chan = "0.1"
crossbeam = "0.3"
futures = "0.1"
futures-cpupool = "0.1"
error-chain = "0.8"
owning_ref = "0.3"
stable_deref_trait = "1.0.0"
rust-stemmers = "0.1.0"
downcast = { version="0.9", features = ["nightly"]}
matches = "0.1"
snap = "0.2"
bitpacking = "*"

[target.'cfg(windows)'.dependencies]
winapi = "0.2"

[dev-dependencies]
rand = "0.3"
tempfile = "2.1"
env_logger = "0.4"

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false


[features]
default = ["mmap"]
streamdict = []
mmap = ["fst/mmap", "atomicwrites"]


[badges]
travis-ci = { repository = "tantivy-search/tantivy" }

[[example]]
name = "simple_search"
required-features = ["mmap"]


[[bin]]
name = "convert_to_static"
path = "./bin/convert_to_static.rs"

